version: '3.3'

services: 
  application:
    build:
      context: .
    restart: unless-stopped
    volumes:
      - ./database:/app/data
    container_name: logging
    ports:
      - 2323:2323
    network_mode: host